<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week_3%2C4%2C5_MDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving Simple_100_Student_Marks[1].csv to Simple_100_Student_Marks[1].csv

In [7]:
df = pd.read_csv("Simple_100_Student_Marks[1].csv")

In [8]:
df

,student_name,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
0,Mr. Gregory Homenick,69,24,52,4,83
1,Marlene Leffler IV,62,59,70,54,52
2,Josephine Ebert,29,76,13,8,19
3,Dr. Irene Green,44,66,14,2,14
4,Jake Huel,49,23,63,86,68
...,...,...,...,...,...,...
95,Renee Schinner,69,99,73,62,32
96,Marguerite Ebert,32,62,82,99,42
97,Jorge Bednar,77,56,46,79,25
98,Mrs. Roxanne Jacobi,54,66,70,49,20
99,Dean Schowalter,28,49,78,80,79

In [9]:
df.head(10)

,student_name,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
0,Mr. Gregory Homenick,69,24,52,4,83
1,Marlene Leffler IV,62,59,70,54,52
2,Josephine Ebert,29,76,13,8,19
3,Dr. Irene Green,44,66,14,2,14
4,Jake Huel,49,23,63,86,68
5,Ralph Schuster,69,28,55,37,77
6,Lila Schmidt,91,10,19,55,38
7,Ms. Naomi Rau,65,70,83,3,25
8,Maryann Marquardt,28,31,27,75,37
9,Edna Von,11,51,86,77,11

In [10]:
df.tail(10)

,student_name,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
90,Amber Windler,88,50,49,77,24
91,Leticia Senger III,81,90,66,15,21
92,Mr. Patrick Mueller,81,81,5,45,36
93,Cedric Bergstrom Jr.,49,74,36,57,66
94,Elizabeth Ward,73,91,72,33,44
95,Renee Schinner,69,99,73,62,32
96,Marguerite Ebert,32,62,82,99,42
97,Jorge Bednar,77,56,46,79,25
98,Mrs. Roxanne Jacobi,54,66,70,49,20
99,Dean Schowalter,28,49,78,80,79

In [19]:

print(df.shape)
print(df.index)
print(df.columns)
print(df.info())

(100, 6)
RangeIndex(start=0, stop=100, step=1)
Index(['student_name', 'maths_marks', 'science_marks', 'english_marks',
       'social_studies_marks', 'language_marks'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_name          100 non-null    object
 1   maths_marks           100 non-null    int64
 2   science_marks         100 non-null    int64
 3   english_marks         100 non-null    int64
 4   social_studies_marks  100 non-null    int64
 5   language_marks        100 non-null    int64
dtypes: int64(5), object(1)
memory usage: 4.8+ KB
None

In [20]:
df[df['maths_marks'] > 50]

,student_name,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
0,Mr. Gregory Homenick,69,24,52,4,83
1,Marlene Leffler IV,62,59,70,54,52
5,Ralph Schuster,69,28,55,37,77
6,Lila Schmidt,91,10,19,55,38
7,Ms. Naomi Rau,65,70,83,3,25
10,Dr. Deborah Harvey,59,23,43,47,73
11,Mrs. Angie Schowalter,88,23,84,52,28
14,Armando Pollich PhD,91,64,38,70,35
15,Marvin Lehner MD,63,20,17,79,39
21,Edith Gorczany,60,48,94,71,98
23,Jonathon Ruecker,99,30,1,21,63
25,Monique Zboncak,88,48,22,63,91
26,Crystal Legros,66,53,42,38,5
29,Tracy D'Amore,67,56,28,82,23
31,Adam Shields,83,88,70,6,58
34,Lonnie Schimmel,64,62,71,48,41
37,Erica Connelly,55,69,2,63,79
38,John Schultz,97,11,52,94,24
39,Lowell Bartell,94,67,63,87,87
40,Marc Hermiston,99,94,38,12,3
42,Rudy Auer,72,71,4,74,31
45,Doyle Thompson,100,40,10,90,12
47,Harry Predovic,78,95,92,7,68
48,Mr. Neil Wunsch,78,83,91,77,34
50,Mr. Rudolph Turner,71,18,78,32,59
52,Donnie Gerlach,52,7,34,87,39
53,Mr. Roy Ernser III,62,48,42,10,55
57,Mrs. Naomi Ernser,58,61,76,38,64
60,Mr. Patrick Crona,65,34,47,83,31
62,Mrs. Claire Bauch,51,26,66,32,8
63,Meghan Jast,79,48,32,3,58
64,Craig Beatty,61,18,33,49,7
65,Phyllis Reilly Jr.,70,41,21,44,44
66,Carole Lubowitz,54,95,79,97,43
67,Andres Lemke,97,78,64,64,82
68,Jeremy Davis,62,10,62,60,33
74,Mr. Grady Kertzmann,70,29,79,23,78
75,Gerardo Kihn,53,9,24,36,31
76,Mr. Gregg Gusikowski,75,72,93,43,31
78,Hilda Treutel,55,64,47,34,47
80,Jessie Mohr,53,43,94,3,21
86,Matthew MacGyver,94,59,91,74,78
87,Marcella Funk,85,98,65,86,16
88,Tommy Mante,80,67,81,32,25
89,Cristina Conn,67,42,32,63,65
90,Amber Windler,88,50,49,77,24
91,Leticia Senger III,81,90,66,15,21
92,Mr. Patrick Mueller,81,81,5,45,36
94,Elizabeth Ward,73,91,72,33,44
95,Renee Schinner,69,99,73,62,32
97,Jorge Bednar,77,56,46,79,25
98,Mrs. Roxanne Jacobi,54,66,70,49,20

In [22]:
df[['student_name', 'maths_marks']]

            student_name  maths_marks
0   Mr. Gregory Homenick           69
1     Marlene Leffler IV           62
2        Josephine Ebert           29
3        Dr. Irene Green           44
4              Jake Huel           49
..                   ...          ...
95        Renee Schinner           69
96      Marguerite Ebert           32
97          Jorge Bednar           77
98   Mrs. Roxanne Jacobi           54
99       Dean Schowalter           28

[100 rows x 2 columns]

In [23]:
df.sort_values('maths_marks')

,student_name,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
12,Shirley Zulauf,2,60,94,53,78
58,Hubert Swaniawski,2,9,43,24,70
83,Eileen Ondricka,2,4,55,74,39
61,Bob Beier,4,40,20,26,70
18,Conrad Greenholt II,5,20,22,21,54
...,...,...,...,...,...,...
38,John Schultz,97,11,52,94,24
67,Andres Lemke,97,78,64,64,82
23,Jonathon Ruecker,99,30,1,21,63
40,Marc Hermiston,99,94,38,12,3
45,Doyle Thompson,100,40,10,90,12

In [24]:
df.describe()

,maths_marks,science_marks,english_marks,social_studies_marks,language_marks
count,100.000000,100.000000,100.00000,100.000000,100.000000
mean,48.950000,56.010000,52.48000,51.510000,46.180000
std,28.999956,26.487846,27.02542,29.081041,23.590522
min,2.000000,4.000000,1.00000,2.000000,3.000000
25%,27.000000,39.500000,32.00000,29.250000,27.000000
50%,52.500000,59.000000,51.00000,52.500000,42.500000
75%,70.250000,76.000000,76.00000,77.000000,65.000000
max,100.000000,99.000000,97.00000,100.000000,98.000000

In [25]:
df['student_name'].count()

np.int64(100)

In [27]:
df.rename(columns={'maths_marks': 'Maths'}, inplace=True)