<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week(9%2C10%2C11)(a)(b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("/hospital_patients_real_world.csv")
display(df.head())

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

In [32]:
# Displaying the number of rows and columns in the DataFrame.
display(df.shape)

(5000, 7)

In [30]:
 # Displaying the column names of the DataFrame.
display(df.columns)

Index(['PatientID', 'Age', 'Gender', 'Diagnosis', 'AdmissionDate',
       'DischargeDate', 'HospitalID'],
      dtype='object')

In [31]:
# Displaying concise summary of the DataFrame, including data types and non-null values.
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      5000 non-null   object
 1   Age            4650 non-null   float64
 2   Gender         4650 non-null   object
 3   Diagnosis      4650 non-null   object
 4   AdmissionDate  5000 non-null   object
 5   DischargeDate  5000 non-null   object
 6   HospitalID     5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

None

In [33]:
# Displaying the count of null values for each column.
print(df.isnull().sum())

PatientID          0
Age              350
Gender           350
Diagnosis        350
AdmissionDate      0
DischargeDate      0
HospitalID         0
dtype: int64

In [34]:
display(df[df.isnull().any(axis=1)]) # Displaying rows that contain any null values.

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
8,PN-5547113,67.0,NaN,Cholelithiasis,2025-05-24,2025-05-26,HOSP-39
18,PN-7747369,NaN,Other,Type 2 Diabetes,2025-08-08,2025-08-10,HOSP-84
19,PN-6459953,NaN,Other,NaN,2024-03-01,2024-03-05,HOSP-15
20,PN-4960664,22.0,Other,NaN,2023-08-08,2023-08-12,HOSP-27
21,PN-5771928,89.0,Other,NaN,2024-03-02,2024-03-10,HOSP-60
...,...,...,...,...,...,...,...
4987,PN-3408515,3.0,Female,NaN,2024-05-18,2024-05-25,HOSP-73
4990,PN-5761970,24.0,Male,NaN,2025-12-23,2025-12-29,HOSP-20
4994,PN-5426856,NaN,Other,ATRIAL FIBRILLATION,2023-11-21,2023-11-28,HOSP-42
4995,PN-3536392,22.0,Female,NaN,2024-03-14,2024-03-18,HOSP-14
4996,PN-8451961,NaN,Other,Myocardial Infarction,2025-03-20,2025-03-21,HOSP-29

In [37]:
#Finding quartiels
QQ1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 23.0
Q3: 72.0
IQR: 49.0

In [39]:
# Display the identified outliers.
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
outliers = df[
    (df["Age"] < lower_limit) |
    (df["Age"] > upper_limit)
]
print("\nDetected Outliers:")
print(outliers)

Detected Outliers:
Empty DataFrame
Columns: [PatientID, Age, Gender, Diagnosis, AdmissionDate, DischargeDate, HospitalID]
Index: []

In [22]:
df_copy = df.copy()

In [24]:
# Original dataset
df = pd.read_csv("/hospital_patients_real_world.csv")

# Copy for dropping missing values
df_drop = df.copy()

# Copy for filling missing values
df_fill = df.copy()

In [27]:
#Drop missing values:
df_drop = df_drop.dropna()

print("After dropping missing values:")
display(df_drop)

After dropping missing values:

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31
...,...,...,...,...,...,...,...
4992,PN-3124888,5.0,Female,Hypertension,2023-12-11,2023-12-17,HOSP-77
4993,PN-1433401,76.0,Unknown,Cholelithiasis,2024-11-03,2024-11-04,HOSP-65
4997,PN-3076032,0.0,Male,Urinary Tract Infection,2023-10-28,2023-10-31,HOSP-83
4998,PN-1714852,29.0,Other,Urinary Tract Infection,2024-08-09,2024-08-16,HOSP-64
4999,PN-4143139,93.0,Other,Cholelithiasis,2024-02-06,2024-02-01,HOSP-82

In [40]:
#Fill missing values:
df_fill["Age"] = df_fill["Age"].fillna(df_fill["Age"].mean())

print("After filling missing Age values:")
display(df_fill)

After filling missing Age values:

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.000000,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.000000,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.000000,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.000000,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.000000,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31
...,...,...,...,...,...,...,...
4995,PN-3536392,22.000000,Female,NaN,2024-03-14,2024-03-18,HOSP-14
4996,PN-8451961,47.384301,Other,Myocardial Infarction,2025-03-20,2025-03-21,HOSP-29
4997,PN-3076032,0.000000,Male,Urinary Tract Infection,2023-10-28,2023-10-31,HOSP-83
4998,PN-1714852,29.000000,Other,Urinary Tract Infection,2024-08-09,2024-08-16,HOSP-64
4999,PN-4143139,93.000000,Other,Cholelithiasis,2024-02-06,2024-02-01,HOSP-82